apiVersion: v1
kind: Secret
metadata:
  name: iot-surveillance-secrets
  namespace: iot-surveillance
type: Opaque
stringData:
  API_KEY_EDGE: "CHANGE_ME_EDGE_KEY"
  API_KEY_DASHBOARD: "CHANGE_ME_DASHBOARD_KEY"
  MINIO_ROOT_USER: "CHANGE_ME_MINIO_USER"
  MINIO_ROOT_PASSWORD: "CHANGE_ME_MINIO_PASSWORD"
  INFLUX_TOKEN: "CHANGE_ME_INFLUX_TOKEN"
  INFLUX_USERNAME: "CHANGE_ME_INFLUX_USER"
  INFLUX_PASSWORD: "CHANGE_ME_INFLUX_PASSWORD"
