apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
type: Opaque
stringData:
  # InfluxDB
  INFLUX_TOKEN: "Nn8dHuXk5odMxrKMzAwQI6OprwI28IgkI3SXYg-ZPE-5_5AwKlzH9uFXvaE9Tr3N7M_64tH2HaMLgii91ub0PQ=="
  INFLUX_ORG: "uminho_mei"
  INFLUX_BUCKET: "Iot_Project"
  
  # Segurança (API Key)
  API_KEY_EDGE: "SeiLa"
  
  # MinIO (Mantive o que me deste, mas lê a nota abaixo!)
  MINIO_ROOT_USER: "admin"
  MINIO_ROOT_PASSWORD: "password123"